name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest black

    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Check code formatting with black
      run: |
        black --check .
      continue-on-error: true

    - name: Run basic import tests
      run: |
        python -c "from src.database import Database; print('Database import successful')"
        python -c "from src.apollo_client import ApolloClient; print('ApolloClient import successful')"
        python -c "from src.gmail_client import GmailClient; print('GmailClient import successful')"
        python -c "from src.template_manager import TemplateManager; print('TemplateManager import successful')"
        python -c "from src.resume_parser import ResumeParser; print('ResumeParser import successful')"
